// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGMSOv82CJCKB7OrqAoqHpLceRSYm2jbU',
    appId: '1:363967479348:web:78efb63d3b5a2ae0441461',
    messagingSenderId: '363967479348',
    projectId: 'playball-22795',
    authDomain: 'playball-22795.firebaseapp.com',
    storageBucket: 'playball-22795.firebasestorage.app',
    measurementId: 'G-28Y9E430RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARg_GkBajU6watsGSlggUFC9YwntM_gNs',
    appId: '1:363967479348:android:55c5fbd30398fdd3441461',
    messagingSenderId: '363967479348',
    projectId: 'playball-22795',
    storageBucket: 'playball-22795.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO2L9wVhqjMfxhfe_B8DbQMY3jw8_7UkM',
    appId: '1:363967479348:ios:650b26f651a5bcae441461',
    messagingSenderId: '363967479348',
    projectId: 'playball-22795',
    storageBucket: 'playball-22795.firebasestorage.app',
    iosBundleId: 'com.example.playball',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO2L9wVhqjMfxhfe_B8DbQMY3jw8_7UkM',
    appId: '1:363967479348:ios:650b26f651a5bcae441461',
    messagingSenderId: '363967479348',
    projectId: 'playball-22795',
    storageBucket: 'playball-22795.firebasestorage.app',
    iosBundleId: 'com.example.playball',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGMSOv82CJCKB7OrqAoqHpLceRSYm2jbU',
    appId: '1:363967479348:web:0ed4f72fd51df804441461',
    messagingSenderId: '363967479348',
    projectId: 'playball-22795',
    authDomain: 'playball-22795.firebaseapp.com',
    storageBucket: 'playball-22795.firebasestorage.app',
    measurementId: 'G-KT3WSWN5W6',
  );
}
